config/routes.rb
Nomicator3::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root 'static_pages#home'

  match '/about', to: 'static_pages#about', via: 'get'

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/models/user.rb
class User < ActiveRecord::Base

  before_save { self.email = email.downcase }
  before_create :create_remember_token

  validates :name, presence: true, length: {maximum: 50}
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
            format: {with: EMAIL_REGEX}, uniqueness: {case_sensitive: false}


  has_secure_password
  validates :password, length: {minimum: 6}

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end


  private

  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid password or no such user' # Not quite right!
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in @user
      flash[:success] = "Welcome to Nomicator, " + @user.name + "!"
      redirect_to @user
    else
      render 'new'
    end

  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  #returns a full page title given a page name
  def full_title(page_title)
    base_title = "Nomicator"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end


end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil

  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=40"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
              data-target="#main-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "N", root_path, id: "logo", class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="main-navbar-collapse">
      <ul class="nav navbar-nav">
        <%#TODO: Make these class = "active" when on the right page     %>
        <li><%= link_to "Home", root_path %></li>
      </ul>
      <ul class="nav navbar-nav">
        <li><%= link_to "About", about_path %></li>
      </ul>
      <% if signed_in? %>
          <%# TODO: Make this pretty %>
          <ul class="nav navbar-nav">
            <li><%= link_to "Profile", current_user %></li>
          </ul>
          <ul class="nav navbar-nav">
            <li><%= link_to "Players", "#" %></li>
          </ul>
          <ul class="nav navbar-nav">
            <li><%= link_to "Documents", "#" %></li>
          </ul>
          <ul class="nav navbar-nav">
            <li><%= link_to "Objects", "#" %></li>
          </ul>
          <ul class="nav navbar-nav">
            <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
          </ul>


      <% else %>
          <ul class="nav navbar-nav">
            <li><%= link_to "Sign in", signin_path %></li>
          </ul>
      <% end %>

    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag "application", media: "all",
                          "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |key, value| %>

      <div class="alert alert-dismissible alert-<%= key %>">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;
        </span><span class="sr-only">Close</span></button>
        <%= value %>
      </div>
  <% end %>
  <%= yield %>
  <br>
  <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>

app/views/shared/_activity_log_form.html.erb
<%= form_for(@activity_log) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class='field'>
      <%= f.text_area :content, placeholder: "Compose new message..." %>
    </div>
    <%= f.submit "Post", class: "btn btn-large btn-primary" %>

<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(object.errors.count, "error") %>.
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
    <ol class="microposts">
      <%= render partial: 'shared/feed_item', collection: @feed_items %>
    </ol>
    <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <span class="content"><%= feed_item.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>
</li>

app/views/shared/_user_info.html.erb
<a href="
  <% user_path(current_user) %>">
  <%= gravatar_for current_user, size: 52 %>
</a>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.activity_logs.count, "action") %>
</span>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<div class="row" xmlns="http://www.w3.org/1999/html">
  <div class="container">
    <h1>Nomicator is a game of Nomic</h1>
    <blockquote class="text-left">
      <p>
        Nomic is a game in which changing the rules is a move. In that respect it differs from almost every other game.
        The primary activity of Nomic is proposing changes in the rules, debating the wisdom of changing them in that
        way, voting on the changes, deciding what can and cannot be done afterwards, and doing it. Even this core of the
        game, of course, can be changed.

        <footer>
          Peter Suber, <cite title="The Paradox of Self-Amendment">The Paradox of Self-Amendment</cite>
        </footer>
      </p>
    </blockquote>
  </div>
</div>
<div class="row">

  <div class="col-md-4">
    <h2>What is Nomicator?</h2>

    <p>
      Nomicator is a game of <a href="http://en.wikipedia.org/wiki/Nomic">Nomic</a>. Nomic is game of law, voting and
      creativity in which the rules
      are continually adjusted by the actions of players. The game starts off with an initial ruleset, but where it goes
      from there is up to the users. The initial rules largely set out a basic system for voting on and editing the
      rules. For where the game is at now, you will need to look at the current <%= link_to "ruleset", "#" %>
    </p>
  </div>

  <div class="col-md-4">
    <h2>Grow-your-own</h2>

    <p>
      Nomic is a meta-game. In fact, all other games are a feasible position in Nomic.
      This makes it especially difficult to make a simulator for Nomic without constant development.
      Nomicator does not attempt to do this, and instead attempts to provide a flexible platform simulating the playing
      of simple tabletop games alongside a system that simulates voting, often the most labour intensive parts.
    </p>
  </div>

  <div class="col-md-4">
    <h2>Roles and responsibilities</h2>

    <p>
      As such, you, the user have a very important role to play in the correct running of the game, just as you would
      if sitting at a table playing. Beyond some basics, players must apply the rules themselves. Nomicator will not
      do this for you. To assist this, Nomicator allows a player to have multiple "Roles" to facilitate this,
      with many actions being possible in those roles instead of "Yourself".
  </div>

</div>

app/views/static_pages/home.html.erb
<% provide(:title, 'Welcome') %>

<div class="jumbotron">
  <div class="panel-body">
    <h1>This is Nomicator</h1>

    <h2>
      Nomic on Rails
    </h2>
    <br>

    <%= link_to "Sign up", signup_path, class: "btn btn-large btn-primary" %>
  </div>
</div>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
      | <%= link_to "delete", user, method: :delete,
                    data: {confirm: "Are you sure?"} %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :email %>
        <%= f.text_field :email %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, "Confirm Password" %>
        <%= f.password_field :password_confirmation %>

        <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>

    <!-- TODO:Add section on roles -->

  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>


<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<br>
<div class="row">
  <div class="col col-md-6">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :password %>
          <%= f.text_field :password, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :password_confirmation, "Confirmation" %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>

        <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>

    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <div class="col-md-4 sidebar">
    <div class="panel panel-primary">
      <div class="panel-heading">

        <%= gravatar_for @user %>
        <%= @user.name %>
      </div>
      <div class="panel-body">
        Player since <%= time_ago_in_words(@user.created_at) %> ago
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <%= @user.name %>'s roles
      </div>
      <div class="panel-body">
        Example Role 1
      </div>
      <div class="panel-body">
        Example Role 2
      </div>
    </div>
  </div>
  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        Example of a user activity post
      </div>
      <div class="panel-body">
        Lorem Ipsum
      </div>
    </div>
  </div>
</div>